"""Fixtures that build a real catalog repository with real signatures.

NOTHING HERE IS A MOCK OF THE CRYPTOGRAPHY. The keypairs are generated by the
real ``minisign`` binary into a temporary directory at test time, and the
signatures are made by that binary too. A test that signed with the same code
that verifies would pass with both halves broken the same way.

NO PRIVATE KEY IS EVER COMMITTED. Every key lives for the length of one test
and dies with its ``tmp_path``. The keys are generated with ``-W``, so they
carry no password and nothing ever prompts on a machine with no terminal.

WHEN THE BINARY IS ABSENT THE TESTS SKIP, WITH A REASON THAT NAMES THE FIX.
A skip is not a pass and the run says so; this is the same posture the
product repo takes for the same reason.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

#: Where the repository root is, from here.
REPO_ROOT = Path(__file__).resolve().parents[2]


def minisign_available() -> bool:
    """Whether the real minisign binary is on the path.

    :returns: True when it can be run.

    Example: minisign_available() -> True
    """
    return shutil.which("minisign") is not None


requires_minisign = pytest.mark.skipif(
    not minisign_available(),
    reason="the real minisign binary is not installed; brew install minisign, "
           "or apt-get install minisign. this is a check that could not run, "
           "which is not a check that passed",
)


def run(*args: str, cwd: Path | None = None) -> str:
    """Run a command and return its stdout, or fail the test loudly.

    :param args: the command and its arguments.
    :param cwd: where to run it.
    :returns: stdout.
    :raises AssertionError: on a non zero exit, carrying stderr, so no test
        ever reads a zero exit from a command whose stderr it discarded.

    Example: run("git", "init", cwd=tmp_path)
    """
    result = subprocess.run(
        list(args), cwd=str(cwd) if cwd else None,
        capture_output=True, text=True, check=False,
    )
    assert result.returncode == 0, (
        f"{' '.join(args)} exited {result.returncode}\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )
    return result.stdout


@pytest.fixture
def keypair(tmp_path: Path) -> dict:
    """Generate one password free minisign keypair for this test.

    :param tmp_path: pytest's per test directory.
    :returns: a dict with ``secret`` and ``public`` paths and the base64
        ``pub`` line the index carries.

    Example: keypair["pub"].startswith("RW") -> True
    """
    secret = tmp_path / "test.key"
    public = tmp_path / "test.pub"
    run("minisign", "-G", "-W", "-s", str(secret), "-p", str(public))
    lines = [line for line in public.read_text().splitlines() if line.strip()]
    return {"secret": secret, "public": public, "pub": lines[-1].strip()}


def sign_bytes(payload: bytes, secret: Path, tmp_path: Path) -> dict:
    """Sign some bytes with minisign and split the result into index fields.

    Description: writes the payload, signs it, and splits the ``.minisig``
      into the four fields the index carries: ``sig`` is line two verbatim,
      ``tc`` is the trusted comment WITHOUT its prefix, and ``gsig`` is
      line four, which is already the base64 of the raw global signature.
    Inputs: payload (bytes) - what to sign. secret (Path) - the key.
      tmp_path (Path) - somewhere to write.
    Output: the four field signature block, plus ``minisig`` with the whole
      file text for the callers that carry one.
    Example: sign_bytes(statement, keypair["secret"], tmp_path)["key_id"]
    """
    import base64
    import hashlib

    message = tmp_path / f"payload-{hashlib.sha256(payload).hexdigest()[:12]}"
    message.write_bytes(payload)
    run("minisign", "-S", "-W", "-s", str(secret), "-m", str(message))
    text = (message.parent / (message.name + ".minisig")).read_text()
    lines = text.splitlines()
    sig_line = lines[1].strip()
    trusted = lines[2].split("trusted comment:", 1)[1].strip()
    global_line = lines[3].strip()
    key_id = base64.b64decode(sig_line)[2:10]
    return {
        "key_id": "".join(f"{byte:02X}" for byte in reversed(key_id)),
        "sig": sig_line,
        "tc": trusted,
        "gsig": global_line,
        "minisig": text,
    }


class StaticServer:
    """A throwaway http server over one directory, on a port the OS picks.

    Used to stand in for the live catalog so the serial rules are exercised
    against a real socket rather than against a patched function. Port 0
    means two tests can never collide on a port, and the thread is a daemon
    so a failed test cannot hang the run.
    """

    def __init__(self, root: Path) -> None:
        """Start serving root on a free port.

        :param root: the directory to serve.
        """
        import functools
        import http.server
        import threading

        handler = functools.partial(
            http.server.SimpleHTTPRequestHandler, directory=str(root)
        )
        self._server = http.server.ThreadingHTTPServer(("127.0.0.1", 0), handler)
        self._thread = threading.Thread(target=self._server.serve_forever, daemon=True)
        self._thread.start()

    @property
    def base_url(self) -> str:
        """The origin this server answers on, with no trailing slash."""
        host, port = self._server.server_address[:2]
        return f"http://{host}:{port}"

    def stop(self) -> None:
        """Shut the server down and join its thread."""
        self._server.shutdown()
        self._server.server_close()
        self._thread.join(timeout=5)


@pytest.fixture
def static_server(tmp_path: Path):
    """Serve a per test directory over http, and stop it afterwards.

    :param tmp_path: pytest's per test directory.
    :returns: a factory taking the directory to serve and returning the
        running server.

    Example: server = static_server(tmp_path / "site")
    """
    started = []

    def start(root: Path) -> StaticServer:
        root.mkdir(parents=True, exist_ok=True)
        server = StaticServer(root)
        started.append(server)
        return server

    yield start
    for server in started:
        server.stop()
